{
   "action": "block ip",
   "asset_id": "30", # this uniquely identifies 
   "config": {
       "app_version": "1.2.9",
       "appname": "-",
       "device": "10.18.2.2",
       "directory": "ciscoasa_0409C19F-FEE2-4D22-879B-96D90619BD6C",
       "enable_password": "",
       "main_module": "ciscoasa_connector.pyc",
       "password": "YTjleuFwkPU8CtrYWF2BEQ==",
       "username": "pix"
   },
   "connector_name": "Cisco ASA",
   "connector_run_id": 136,
   "container_id": 87,
   "container_label": "incident",
   "container_name": "Incident # 1",
   "container_severity": "medium",
   "debug_level": 3,
   "identifier": "block_ip",
   "ipc_version": 1,
   "parameters": [
       {
           "access-list": "inside_access_in",
           "dest": "10.10.10.2",
           "direction": "in",
           "interface": "inside",
           "src": "any"
       }
   ],
   "phantom_version": "1.2.265",
   "session_id": "822e7767-25ac-49ed-8d21-115840cb6aa9"
}